# The registry is generated by the checked-in inventory pass.
# Re-run the area inventory process and update client/src/data/ecosystemAreas.ts
# when a route family or backend contract materially changes.
from pathlib import Path
path = Path("client/src/data/ecosystemAreas.ts")
print(f"Canonical registry: {path} ({path.read_text().count('id:')} areas)")
